import { SpeakerButton } from "@/components/app/SpeakerButton";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { localApi } from "@/lib/local-api";
import { offlineLookup } from "@/lib/offline-dictionary";
import { saveWord } from "@/lib/study";
import { BookmarkCheck, Loader2, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
export interface WordSelection { word:string; display:string; example:string; sourceTitle?:string; language?:string }
interface SavedWordEntry { _id:string; word:string; display:string; definition:string; example:string; sourceTitle?:string; language?:string }
interface Props { open:boolean; onOpenChange:(open:boolean)=>void; selection:WordSelection|null; existing?:SavedWordEntry|null; onSaved?:()=>void }
export function WordDialog({open,onOpenChange,selection,existing,onSaved}:Props){
 const [definition,setDefinition]=useState(""); const [example,setExample]=useState(""); const [isLookingUp,setIsLookingUp]=useState(false); const [lookupDone,setLookupDone]=useState(false); const [lookupFailed,setLookupFailed]=useState(false); const [lookupSource,setLookupSource]=useState<null|"offline"|"online">(null); const [isSaving,setIsSaving]=useState(false);
 useEffect(()=>{if(!open||!selection)return;setDefinition(existing?.definition??"");setExample(existing?.example??selection.example);setLookupDone(Boolean(existing));setLookupFailed(false);setLookupSource(null);if(existing)return;let cancelled=false;const offline=offlineLookup(selection.word);if(offline){setDefinition(offline.definition);if(!selection.example&&offline.example)setExample(offline.example);setLookupSource("offline");setLookupDone(true);return;}let cancelled2=false;setIsLookingUp(true);localApi.dictionary(selection.word).then((r)=>{if(cancelled2)return;if(r?.definition){setDefinition(r.definition);setLookupSource("online");}else{setLookupFailed(true);}if(r?.example&&!selection.example)setExample(r.example);}).catch(()=>{if(!cancelled2)setLookupFailed(true);}).finally(()=>{if(!cancelled2){setIsLookingUp(false);setLookupDone(true);}});return()=>{cancelled=true;cancelled2=true};},[open,selection,existing]);
 const save=async()=>{if(!selection)return;setIsSaving(true);try{if(existing){await localApi.words.save({word:selection.word,display:selection.display,definition,example,sourceTitle:selection.sourceTitle,language:selection.language});toast.success("Word updated");}else{const res=await saveWord({word:selection.word,display:selection.display,definition,example,sourceTitle:selection.sourceTitle,language:selection.language});if(res.saved)toast.success("Saved — Anki card generated automatically");if(res.skipped){onOpenChange(false);return;}}onOpenChange(false);onSaved?.();}catch{toast.error("Could not save the word.")}finally{setIsSaving(false)}};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle className="flex items-center gap-2 text-xl"><span className="rounded-md bg-primary/10 px-2.5 py-0.5 text-primary">{selection?.display??""}</span>{selection&&<SpeakerButton text={selection.display} lang={selection.language??existing?.language} label="Pronounce word"/>}</DialogTitle><DialogDescription>{existing?"Already in your vocabulary — update it locally.":"Save this word and a local Anki card is generated automatically."}</DialogDescription></DialogHeader><div className="flex flex-col gap-4"><div className="flex flex-col gap-2"><div className="flex items-center gap-2"><Label htmlFor="word-definition">Definition</Label>{isLookingUp&&<span className="flex items-center gap-1.5 text-xs text-muted-foreground"><Loader2 className="size-3 animate-spin"/>Looking it up…</span>}{!isLookingUp&&lookupDone&&!definition&&<Badge variant={lookupFailed?"outline":"secondary"}>{lookupFailed?"Offline — add your own":""}</Badge>}{lookupSource==="offline"&&<Badge variant="secondary" className="gap-1"><Sparkles className="size-3"/>Offline dictionary</Badge>}</div><Textarea id="word-definition" value={definition} onChange={(e)=>setDefinition(e.target.value)} placeholder="Type the meaning in your own words" className="min-h-20 resize-none"/>{lookupFailed&&<p className="text-[11px] text-muted-foreground">Online dictionary is unreachable (you appear to be offline). The offline starter dictionary covers common words; for anything else, add your own definition — it still generates an Anki card.</p>}</div><div className="flex flex-col gap-2"><Label htmlFor="word-example">Example sentence</Label><Textarea id="word-example" value={example} onChange={(e)=>setExample(e.target.value)} className="min-h-16 resize-none"/></div></div><DialogFooter><Button variant="ghost" onClick={()=>onOpenChange(false)} disabled={isSaving}>Cancel</Button><Button onClick={()=>void save()} disabled={isSaving||!selection} className="gap-2">{isSaving?<Loader2 className="size-4 animate-spin"/>:existing?<BookmarkCheck className="size-4"/>:<Sparkles className="size-4"/>}{isSaving?"Saving…":existing?"Update word":"Save word"}</Button></DialogFooter></DialogContent></Dialog>;
}
